# Generated by Django 5.1.7 on 2025-03-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waypointType', models.CharField(choices=[('Pickup', 'PICKUP'), ('Delivery', 'DELIVERY')], default='Pickup', max_length=10)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-location',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(max_length=50)),
                ('customerName', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('waypoints', models.ManyToManyField(to='orders.waypoint')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
