# Generated by Django 5.1.7 on 2025-03-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='orderNumber',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
